In [16]:
# Adaptado de http://docs.opencv.org/3.2.0/df/d9d/tutorial_py_colorspaces.html
import numpy as np
import cv2

# img_BGR = cv2.imread("mms.jpg") #obtida de http://blogs.mathworks.com/images/steve/2010/mms.jpg
img_BGR = cv2.imread("balas_s.png")
img_buffer = img_BGR

# kernel = np.ones((5,5), np.uint8)
# img_buffer = cv2.erode(img_BGR, kernel,iterations = 1)
# img_buffer = cv2.dilate(img_buffer, kernel,iterations = 1)

# Convert BGR to HSV
img_HSV = cv2.cvtColor(img_buffer, cv2.COLOR_BGR2HSV)
# -----------------------------------------------------------------------------------------------------------------------

# define range of blue color in HSV
# importante: faixa da componente H no OpenCV: [0, 179]

red = 0

green = red + 60
if green > 179:
    green = green - 180

blue = green + 60
if blue > 179:
    blue = blue - 180
    
    
thres=30
lower_blue = np.array([blue-thres, 50, 50])
upper_blue = np.array([blue+thres, 255, 255])

lower_green = np.array([green-thres, 50, 20])
upper_green = np.array([green+thres, 255, 255])

lower_red = np.array([red-thres, 50, 50])
upper_red = np.array([red+thres, 255, 255])

# Threshold the HSV image to get only blue colors
mask_blue = cv2.inRange(img_HSV, lower_blue, upper_blue)
mask_green = cv2.inRange(img_HSV, lower_green, upper_green)
mask_red = cv2.inRange(img_HSV, lower_red, upper_red)

# mask = mask_blue;
mask = mask_green;
# mask = mask_red;

kernel = np.ones((5,5), np.uint8)
erosion = cv2.erode(mask, kernel, iterations = 3)
#erosion=mask

# Bitwise-AND mask and original image
imgRes = cv2.bitwise_and(img_BGR, img_BGR, mask= erosion)

# find all blobs and label them
n, labels, stats, centroids = cv2.connectedComponentsWithStats(erosion)
print centroids
print stats
font = cv2.FONT_HERSHEY_SIMPLEX

for n in range(1,len(stats)): #o primeiro (índice 0) é a imagem toda, então, desconsiderar
    cv2.rectangle(imgRes, (stats[n][0],stats[n][1]), (stats[n][0]+stats[n][2],stats[n][1]+stats[n][3]),(255,255,255),2)
    cv2.putText(imgRes, str(n),(stats[n][0], stats[n][1]), font, 1,(255, 255, 255), 2, cv2.LINE_AA)
    cv2.circle(imgRes, (int(centroids[n][0]), int(centroids[n][1])), 3, (0, 0, 255), -1)
    
cv2.putText(imgRes,'Total: '+str(n),(0, stats[0][3]), font, 1,(255,255,255),2,cv2.LINE_AA)
#cv2.imwrite('colorlabels.jpg',res) #para gravar a imagem
cv2.imshow('img_BGR', img_BGR)
cv2.imshow('img_buffer', img_buffer)
cv2.imshow('erosion', erosion)
cv2.imshow('imgRes', imgRes)

cv2.imwrite( "imgOut_BGR.jpg", img_BGR);
cv2.imwrite('img_buffer.jpg', img_buffer)
cv2.imwrite( "imgOut_erosion.jpg", erosion);
cv2.imwrite( "imgOut_imgRes.jpg", imgRes);
# -----------------------------------------------------------------------------------------------------------------------
cv2.waitKey(0)
cv2.destroyAllWindows()

[[249.49764412 249.2517338 ]
 [157.5         66.5       ]
 [ 80.29268293  86.        ]
 [117.67857143  88.39285714]
 [170.66666667  96.        ]
 [ 63.64285714 126.64285714]
 [ 84.8125     146.        ]
 [141.5        146.5       ]
 [139.5        149.5       ]
 [206.31578947 158.42105263]
 [290.25       176.09615385]
 [141.45652174 207.45652174]
 [398.47058824 307.05882353]
 [184.61904762 336.33333333]
 [306.90697674 353.30232558]
 [150.2        358.4       ]
 [130.48333333 365.96666667]
 [308.05769231 373.11538462]
 [438.84782609 378.2826087 ]
 [389.39655172 386.43103448]
 [117.2        401.64347826]
 [355.93333333 425.7       ]
 [151.         428.5       ]
 [398.16455696 447.49367089]
 [345.97368421 453.68421053]]
[[     0      0    500    500 249164]
 [   155     64      6      6      6]
 [    75     83     11      7     41]
 [   116     83      5     12     28]
 [   169     93      4      7     12]
 [    61    125      6      5     14]
 [    83    143      5      6     16]
 [   141